config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "home#home"
  post '/home/create_event_a', to: 'home#create_event_a'
  post '/home/create_event_b', to: 'home#create_event_b'
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # validating the user
    def validate_user
        if current_user.blank?
            redirect_to new_user_registration_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :validate_user, :intialize_instance
    def home
    end
   
    # Initializing the eventA
    def create_event_a
        flash[:notice] = 'EventA has been initilaized'
        redirect_to root_path
    rescue StandardError => e
        flash[:notice] = e.message
        redirect_to root_path
    end

    # Initializing the EventB and Sending Email
    def create_event_b
        @event.for_email(current_user.email)
        flash[:notice] = "EventB has been initialized and sent email for #{current_user.email}."
        redirect_to root_path
    rescue StandardError => e
        flash[:notice] = e.message
        redirect_to root_path
    end
    
    def intialize_instance
        @event = Iterable::Events.new
    rescue StandardError => e
        flash[:notice] = e.message
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<div style="margin-top: 30vh; margin-left: 40vh;">
    <div class="row">
        <div class="col">
            <%= button_to 'Create EventA', home_create_event_a_path, class: "btn btn-primary", method: :post, remote: true %>
        </div>
        <div class="col">
            <%= button_to 'Create EventB', home_create_event_b_path, class: "btn btn-primary", method: :post, remote: true %>
        </div>
    </div>
    <div class="row" style="margin-left: 35vh; margin-top: 10vh;">
        <%= button_to 'Logout', destroy_user_session_path, class: "btn btn-secondary", method: :delete%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IterableProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="container">
      <% if flash[:notice].present? %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong><%= flash[:notice] %></strong>
        </div>
      <% elsif flash[:alert].present? %>
         <strong><%= flash[:alert] %></strong>
      <%end%>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>